;
; Class file 'D:\PRTGRAPH\som\vxrexx.cls'
;

version 210
load somobj.cls
load core.cls
load visible.cls
load submenu.cls
load menubar.cls
load appobj.cls
load screen.cls
load menuit.cls
load primiti.cls
load manager.cls
load window.cls
load group.cls
load notebk.cls
load mle.cls
load contain.cls
load button.cls
load listbox.cls
load entryfl.cls
load combo.cls
load desctxt.cls
load pictbox.cls
load spin.cls
load slider.cls
load value.cls
load vrchart.cls
load client.cls
load timer.cls
load query.cls
load connect.cls
load printer.cls
load combobx.cls
load dropdn.cls
load pbutton.cls
load checkbx.cls
load rbutton.cls
load irbutn.cls
load ipbutn.cls


;
; End of class file
;
