
/*
 * This file was generated by the SOM Compiler.
 * FileName: printer.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef printer_h
#define printer_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef VRPrinter
#define VRPrinter SOMAny
#endif
#include "desctxt.h"

/*
 * Passthru lines: File: "C.h", "after"
 */

#include "vrprint.h"
#include "d:\prtgraph\prt_int.h"
#include "d:\prtgraph\prt_dlg.h"
#define  WM_INITCAP  (WM_USER + 10)

#ifdef __WATCOMC__
    #pragma aux VRPrinterCClassData "*"
    #pragma aux VRPrinterClassData "*"
    #pragma aux M_VRPrinterCClassData "*"
    #pragma aux M_VRPrinterClassData "*"
#endif

#define VRPrinter_MajorVersion 1
#define VRPrinter_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define VRPrinterNewClass c
#pragma linkage(c, system)
#define VRPrinterClassData d
#define VRPrinterCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define VRPrinter_classObj VRPrinterClassData.classObject
#define _VRPrinter VRPrinter_classObj

/*
 * New and Renew macros for VRPrinter
 */
#define _VRPrinterNew() (_somNew(VRPrinterClassData.classObject))
#define VRPrinterNew() \
	( VRPrinterClassData.classObject \
		? _VRPrinterNew() \
		: ( VRPrinterNewClass(VRPrinter_MajorVersion, VRPrinter_MinorVersion), _VRPrinterNew() ) )
#define VRPrinterRenew(buf) \
	( _somRenew(VRPrinterClassData.classObject, buf) )

/*
 * Override method: somInit
 */
#define VRPrinter_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * Override method: somUninit
 */
#define VRPrinter_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * Override method: vrLocalCreateWindow
 */
#define VRPrinter_vrLocalCreateWindow(somSelf,visible) \
	VRCore_vrLocalCreateWindow(somSelf,visible)

/*
 * Override method: vrSet_WordBreak
 */
#define VRPrinter_vrSet_WordBreak(somSelf,on) \
	VRDescriptiveText_vrSet_WordBreak(somSelf,on)

/*
 * Override method: vrGet_WordBreak
 */
#define VRPrinter_vrGet_WordBreak(somSelf,on) \
	VRDescriptiveText_vrGet_WordBreak(somSelf,on)

/*
 * New Method: vrStemFetchLong
 */
typedef ULONG    SOMLINK somTP_VRPrinter_vrStemFetchLong(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PBOOL pOk);
#pragma linkage(somTP_VRPrinter_vrStemFetchLong, system)
typedef somTP_VRPrinter_vrStemFetchLong *somTD_VRPrinter_vrStemFetchLong;
#define somMD_VRPrinter_vrStemFetchLong "----"
#define VRPrinter_vrStemFetchLong(somSelf,pszStem,index,pOk) \
    (SOM_Resolve(somSelf, VRPrinter, vrStemFetchLong) \
	(somSelf,pszStem,index,pOk))
#define _vrStemFetchLong VRPrinter_vrStemFetchLong

/*
 * New Method: vrStemFetchString
 */
typedef PSZ    SOMLINK somTP_VRPrinter_vrStemFetchString(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PBOOL pOk);
#pragma linkage(somTP_VRPrinter_vrStemFetchString, system)
typedef somTP_VRPrinter_vrStemFetchString *somTD_VRPrinter_vrStemFetchString;
#define somMD_VRPrinter_vrStemFetchString "----"
#define VRPrinter_vrStemFetchString(somSelf,pszStem,index,pOk) \
    (SOM_Resolve(somSelf, VRPrinter, vrStemFetchString) \
	(somSelf,pszStem,index,pOk))
#define _vrStemFetchString VRPrinter_vrStemFetchString

/*
 * New Method: vrStemSetValue
 */
typedef BOOL    SOMLINK somTP_VRPrinter_vrStemSetValue(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PSZ pszValue);
#pragma linkage(somTP_VRPrinter_vrStemSetValue, system)
typedef somTP_VRPrinter_vrStemSetValue *somTD_VRPrinter_vrStemSetValue;
#define somMD_VRPrinter_vrStemSetValue "----"
#define VRPrinter_vrStemSetValue(somSelf,pszStem,index,pszValue) \
    (SOM_Resolve(somSelf, VRPrinter, vrStemSetValue) \
	(somSelf,pszStem,index,pszValue))
#define _vrStemSetValue VRPrinter_vrStemSetValue

/*
 * New Method: vrStemSetValueLong
 */
typedef BOOL    SOMLINK somTP_VRPrinter_vrStemSetValueLong(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		ULONG ulValue);
#pragma linkage(somTP_VRPrinter_vrStemSetValueLong, system)
typedef somTP_VRPrinter_vrStemSetValueLong *somTD_VRPrinter_vrStemSetValueLong;
#define somMD_VRPrinter_vrStemSetValueLong "----"
#define VRPrinter_vrStemSetValueLong(somSelf,pszStem,index,ulValue) \
    (SOM_Resolve(somSelf, VRPrinter, vrStemSetValueLong) \
	(somSelf,pszStem,index,ulValue))
#define _vrStemSetValueLong VRPrinter_vrStemSetValueLong

/*
 * New Method: vrGet_LeftMargin
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_LeftMargin(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_LeftMargin, system)
typedef somTP_VRPrinter_vrGet_LeftMargin *somTD_VRPrinter_vrGet_LeftMargin;
#define somMD_VRPrinter_vrGet_LeftMargin "----"
#define VRPrinter_vrGet_LeftMargin(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_LeftMargin) \
	(somSelf,val))
#define _vrGet_LeftMargin VRPrinter_vrGet_LeftMargin

/*
 * New Method: vrGet_RightMargin
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_RightMargin(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_RightMargin, system)
typedef somTP_VRPrinter_vrGet_RightMargin *somTD_VRPrinter_vrGet_RightMargin;
#define somMD_VRPrinter_vrGet_RightMargin "----"
#define VRPrinter_vrGet_RightMargin(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_RightMargin) \
	(somSelf,val))
#define _vrGet_RightMargin VRPrinter_vrGet_RightMargin

/*
 * New Method: vrGet_TopMargin
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_TopMargin(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_TopMargin, system)
typedef somTP_VRPrinter_vrGet_TopMargin *somTD_VRPrinter_vrGet_TopMargin;
#define somMD_VRPrinter_vrGet_TopMargin "----"
#define VRPrinter_vrGet_TopMargin(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_TopMargin) \
	(somSelf,val))
#define _vrGet_TopMargin VRPrinter_vrGet_TopMargin

/*
 * New Method: vrGet_BottomMargin
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_BottomMargin(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_BottomMargin, system)
typedef somTP_VRPrinter_vrGet_BottomMargin *somTD_VRPrinter_vrGet_BottomMargin;
#define somMD_VRPrinter_vrGet_BottomMargin "----"
#define VRPrinter_vrGet_BottomMargin(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_BottomMargin) \
	(somSelf,val))
#define _vrGet_BottomMargin VRPrinter_vrGet_BottomMargin

/*
 * New Method: vrGet_PageWidth
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_PageWidth(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_PageWidth, system)
typedef somTP_VRPrinter_vrGet_PageWidth *somTD_VRPrinter_vrGet_PageWidth;
#define somMD_VRPrinter_vrGet_PageWidth "----"
#define VRPrinter_vrGet_PageWidth(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_PageWidth) \
	(somSelf,val))
#define _vrGet_PageWidth VRPrinter_vrGet_PageWidth

/*
 * New Method: vrGet_PageHeight
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_PageHeight(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_PageHeight, system)
typedef somTP_VRPrinter_vrGet_PageHeight *somTD_VRPrinter_vrGet_PageHeight;
#define somMD_VRPrinter_vrGet_PageHeight "----"
#define VRPrinter_vrGet_PageHeight(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_PageHeight) \
	(somSelf,val))
#define _vrGet_PageHeight VRPrinter_vrGet_PageHeight

/*
 * New Method: vrGet_Printing
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_Printing(VRPrinter *somSelf,
		BOOL *on);
#pragma linkage(somTP_VRPrinter_vrGet_Printing, system)
typedef somTP_VRPrinter_vrGet_Printing *somTD_VRPrinter_vrGet_Printing;
#define somMD_VRPrinter_vrGet_Printing "----"
#define VRPrinter_vrGet_Printing(somSelf,on) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_Printing) \
	(somSelf,on))
#define _vrGet_Printing VRPrinter_vrGet_Printing

/*
 * New Method: vrGet_CurrentPrinter
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_CurrentPrinter(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_CurrentPrinter, system)
typedef somTP_VRPrinter_vrGet_CurrentPrinter *somTD_VRPrinter_vrGet_CurrentPrinter;
#define somMD_VRPrinter_vrGet_CurrentPrinter "----"
#define VRPrinter_vrGet_CurrentPrinter(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_CurrentPrinter) \
	(somSelf,str))
#define _vrGet_CurrentPrinter VRPrinter_vrGet_CurrentPrinter

/*
 * New Method: vrGet_CurrentDevice
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_CurrentDevice(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_CurrentDevice, system)
typedef somTP_VRPrinter_vrGet_CurrentDevice *somTD_VRPrinter_vrGet_CurrentDevice;
#define somMD_VRPrinter_vrGet_CurrentDevice "----"
#define VRPrinter_vrGet_CurrentDevice(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_CurrentDevice) \
	(somSelf,str))
#define _vrGet_CurrentDevice VRPrinter_vrGet_CurrentDevice

/*
 * New Method: vrSet_LineSpace
 */
typedef bool    SOMLINK somTP_VRPrinter_vrSet_LineSpace(VRPrinter *somSelf,
		ULONG val);
#pragma linkage(somTP_VRPrinter_vrSet_LineSpace, system)
typedef somTP_VRPrinter_vrSet_LineSpace *somTD_VRPrinter_vrSet_LineSpace;
#define somMD_VRPrinter_vrSet_LineSpace "----"
#define VRPrinter_vrSet_LineSpace(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrSet_LineSpace) \
	(somSelf,val))
#define _vrSet_LineSpace VRPrinter_vrSet_LineSpace

/*
 * New Method: vrGet_LineSpace
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_LineSpace(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_LineSpace, system)
typedef somTP_VRPrinter_vrGet_LineSpace *somTD_VRPrinter_vrGet_LineSpace;
#define somMD_VRPrinter_vrGet_LineSpace "----"
#define VRPrinter_vrGet_LineSpace(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_LineSpace) \
	(somSelf,val))
#define _vrGet_LineSpace VRPrinter_vrGet_LineSpace

/*
 * New Method: vrGet_Version
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_Version(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_Version, system)
typedef somTP_VRPrinter_vrGet_Version *somTD_VRPrinter_vrGet_Version;
#define somMD_VRPrinter_vrGet_Version "----"
#define VRPrinter_vrGet_Version(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_Version) \
	(somSelf,str))
#define _vrGet_Version VRPrinter_vrGet_Version

/*
 * New Method: vrSet_PrintColor
 */
typedef bool    SOMLINK somTP_VRPrinter_vrSet_PrintColor(VRPrinter *somSelf,
		PSZ str);
#pragma linkage(somTP_VRPrinter_vrSet_PrintColor, system)
typedef somTP_VRPrinter_vrSet_PrintColor *somTD_VRPrinter_vrSet_PrintColor;
#define somMD_VRPrinter_vrSet_PrintColor "----"
#define VRPrinter_vrSet_PrintColor(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrSet_PrintColor) \
	(somSelf,str))
#define _vrSet_PrintColor VRPrinter_vrSet_PrintColor

/*
 * New Method: vrGet_PrintColor
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_PrintColor(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_PrintColor, system)
typedef somTP_VRPrinter_vrGet_PrintColor *somTD_VRPrinter_vrGet_PrintColor;
#define somMD_VRPrinter_vrGet_PrintColor "----"
#define VRPrinter_vrGet_PrintColor(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_PrintColor) \
	(somSelf,str))
#define _vrGet_PrintColor VRPrinter_vrGet_PrintColor

/*
 * New Method: vrSet_ColorEnabled
 */
typedef bool    SOMLINK somTP_VRPrinter_vrSet_ColorEnabled(VRPrinter *somSelf,
		BOOL on);
#pragma linkage(somTP_VRPrinter_vrSet_ColorEnabled, system)
typedef somTP_VRPrinter_vrSet_ColorEnabled *somTD_VRPrinter_vrSet_ColorEnabled;
#define somMD_VRPrinter_vrSet_ColorEnabled "----"
#define VRPrinter_vrSet_ColorEnabled(somSelf,on) \
    (SOM_Resolve(somSelf, VRPrinter, vrSet_ColorEnabled) \
	(somSelf,on))
#define _vrSet_ColorEnabled VRPrinter_vrSet_ColorEnabled

/*
 * New Method: vrGet_ColorEnabled
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_ColorEnabled(VRPrinter *somSelf,
		BOOL *on);
#pragma linkage(somTP_VRPrinter_vrGet_ColorEnabled, system)
typedef somTP_VRPrinter_vrGet_ColorEnabled *somTD_VRPrinter_vrGet_ColorEnabled;
#define somMD_VRPrinter_vrGet_ColorEnabled "----"
#define VRPrinter_vrGet_ColorEnabled(somSelf,on) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_ColorEnabled) \
	(somSelf,on))
#define _vrGet_ColorEnabled VRPrinter_vrGet_ColorEnabled

/*
 * New Method: vrSet_Measures
 */
typedef bool    SOMLINK somTP_VRPrinter_vrSet_Measures(VRPrinter *somSelf,
		PSZ str);
#pragma linkage(somTP_VRPrinter_vrSet_Measures, system)
typedef somTP_VRPrinter_vrSet_Measures *somTD_VRPrinter_vrSet_Measures;
#define somMD_VRPrinter_vrSet_Measures "----"
#define VRPrinter_vrSet_Measures(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrSet_Measures) \
	(somSelf,str))
#define _vrSet_Measures VRPrinter_vrSet_Measures

/*
 * New Method: vrGet_Measures
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_Measures(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_Measures, system)
typedef somTP_VRPrinter_vrGet_Measures *somTD_VRPrinter_vrGet_Measures;
#define somMD_VRPrinter_vrGet_Measures "----"
#define VRPrinter_vrGet_Measures(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_Measures) \
	(somSelf,str))
#define _vrGet_Measures VRPrinter_vrGet_Measures

/*
 * New Method: vrGet_PageNum
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_PageNum(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_PageNum, system)
typedef somTP_VRPrinter_vrGet_PageNum *somTD_VRPrinter_vrGet_PageNum;
#define somMD_VRPrinter_vrGet_PageNum "----"
#define VRPrinter_vrGet_PageNum(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_PageNum) \
	(somSelf,val))
#define _vrGet_PageNum VRPrinter_vrGet_PageNum

/*
 * New Method: vrGet_JobName
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_JobName(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_JobName, system)
typedef somTP_VRPrinter_vrGet_JobName *somTD_VRPrinter_vrGet_JobName;
#define somMD_VRPrinter_vrGet_JobName "----"
#define VRPrinter_vrGet_JobName(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_JobName) \
	(somSelf,str))
#define _vrGet_JobName VRPrinter_vrGet_JobName

/*
 * New Method: vrGet_DefaultPrinter
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_DefaultPrinter(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_DefaultPrinter, system)
typedef somTP_VRPrinter_vrGet_DefaultPrinter *somTD_VRPrinter_vrGet_DefaultPrinter;
#define somMD_VRPrinter_vrGet_DefaultPrinter "----"
#define VRPrinter_vrGet_DefaultPrinter(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_DefaultPrinter) \
	(somSelf,str))
#define _vrGet_DefaultPrinter VRPrinter_vrGet_DefaultPrinter

/*
 * New Method: vrGet_MinLeftMar
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_MinLeftMar(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_MinLeftMar, system)
typedef somTP_VRPrinter_vrGet_MinLeftMar *somTD_VRPrinter_vrGet_MinLeftMar;
#define somMD_VRPrinter_vrGet_MinLeftMar "----"
#define VRPrinter_vrGet_MinLeftMar(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_MinLeftMar) \
	(somSelf,val))
#define _vrGet_MinLeftMar VRPrinter_vrGet_MinLeftMar

/*
 * New Method: vrGet_MinRightMar
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_MinRightMar(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_MinRightMar, system)
typedef somTP_VRPrinter_vrGet_MinRightMar *somTD_VRPrinter_vrGet_MinRightMar;
#define somMD_VRPrinter_vrGet_MinRightMar "----"
#define VRPrinter_vrGet_MinRightMar(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_MinRightMar) \
	(somSelf,val))
#define _vrGet_MinRightMar VRPrinter_vrGet_MinRightMar

/*
 * New Method: vrGet_MinTopMar
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_MinTopMar(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_MinTopMar, system)
typedef somTP_VRPrinter_vrGet_MinTopMar *somTD_VRPrinter_vrGet_MinTopMar;
#define somMD_VRPrinter_vrGet_MinTopMar "----"
#define VRPrinter_vrGet_MinTopMar(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_MinTopMar) \
	(somSelf,val))
#define _vrGet_MinTopMar VRPrinter_vrGet_MinTopMar

/*
 * New Method: vrGet_MinBottomMar
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_MinBottomMar(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_MinBottomMar, system)
typedef somTP_VRPrinter_vrGet_MinBottomMar *somTD_VRPrinter_vrGet_MinBottomMar;
#define somMD_VRPrinter_vrGet_MinBottomMar "----"
#define VRPrinter_vrGet_MinBottomMar(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_MinBottomMar) \
	(somSelf,val))
#define _vrGet_MinBottomMar VRPrinter_vrGet_MinBottomMar

/*
 * New Method: vrGet_FormName
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_FormName(VRPrinter *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRPrinter_vrGet_FormName, system)
typedef somTP_VRPrinter_vrGet_FormName *somTD_VRPrinter_vrGet_FormName;
#define somMD_VRPrinter_vrGet_FormName "----"
#define VRPrinter_vrGet_FormName(somSelf,str) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_FormName) \
	(somSelf,str))
#define _vrGet_FormName VRPrinter_vrGet_FormName

/*
 * New Method: vrGet_FormWidth
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_FormWidth(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_FormWidth, system)
typedef somTP_VRPrinter_vrGet_FormWidth *somTD_VRPrinter_vrGet_FormWidth;
#define somMD_VRPrinter_vrGet_FormWidth "----"
#define VRPrinter_vrGet_FormWidth(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_FormWidth) \
	(somSelf,val))
#define _vrGet_FormWidth VRPrinter_vrGet_FormWidth

/*
 * New Method: vrGet_FormHeight
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_FormHeight(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_FormHeight, system)
typedef somTP_VRPrinter_vrGet_FormHeight *somTD_VRPrinter_vrGet_FormHeight;
#define somMD_VRPrinter_vrGet_FormHeight "----"
#define VRPrinter_vrGet_FormHeight(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_FormHeight) \
	(somSelf,val))
#define _vrGet_FormHeight VRPrinter_vrGet_FormHeight

/*
 * New Method: vrSet_ShowProgress
 */
typedef bool    SOMLINK somTP_VRPrinter_vrSet_ShowProgress(VRPrinter *somSelf,
		BOOL on);
#pragma linkage(somTP_VRPrinter_vrSet_ShowProgress, system)
typedef somTP_VRPrinter_vrSet_ShowProgress *somTD_VRPrinter_vrSet_ShowProgress;
#define somMD_VRPrinter_vrSet_ShowProgress "----"
#define VRPrinter_vrSet_ShowProgress(somSelf,on) \
    (SOM_Resolve(somSelf, VRPrinter, vrSet_ShowProgress) \
	(somSelf,on))
#define _vrSet_ShowProgress VRPrinter_vrSet_ShowProgress

/*
 * New Method: vrGet_ShowProgress
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_ShowProgress(VRPrinter *somSelf,
		BOOL *on);
#pragma linkage(somTP_VRPrinter_vrGet_ShowProgress, system)
typedef somTP_VRPrinter_vrGet_ShowProgress *somTD_VRPrinter_vrGet_ShowProgress;
#define somMD_VRPrinter_vrGet_ShowProgress "----"
#define VRPrinter_vrGet_ShowProgress(somSelf,on) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_ShowProgress) \
	(somSelf,on))
#define _vrGet_ShowProgress VRPrinter_vrGet_ShowProgress

/*
 * New Method: vrGet_XPos
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_XPos(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_XPos, system)
typedef somTP_VRPrinter_vrGet_XPos *somTD_VRPrinter_vrGet_XPos;
#define somMD_VRPrinter_vrGet_XPos "----"
#define VRPrinter_vrGet_XPos(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_XPos) \
	(somSelf,val))
#define _vrGet_XPos VRPrinter_vrGet_XPos

/*
 * New Method: vrGet_YPos
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_YPos(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_YPos, system)
typedef somTP_VRPrinter_vrGet_YPos *somTD_VRPrinter_vrGet_YPos;
#define somMD_VRPrinter_vrGet_YPos "----"
#define VRPrinter_vrGet_YPos(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_YPos) \
	(somSelf,val))
#define _vrGet_YPos VRPrinter_vrGet_YPos

/*
 * New Method: vrGet_XposTwips
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_XposTwips(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_XposTwips, system)
typedef somTP_VRPrinter_vrGet_XposTwips *somTD_VRPrinter_vrGet_XposTwips;
#define somMD_VRPrinter_vrGet_XposTwips "----"
#define VRPrinter_vrGet_XposTwips(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_XposTwips) \
	(somSelf,val))
#define _vrGet_XposTwips VRPrinter_vrGet_XposTwips

/*
 * New Method: vrGet_YposTwips
 */
typedef bool    SOMLINK somTP_VRPrinter_vrGet_YposTwips(VRPrinter *somSelf,
		PULONG val);
#pragma linkage(somTP_VRPrinter_vrGet_YposTwips, system)
typedef somTP_VRPrinter_vrGet_YposTwips *somTD_VRPrinter_vrGet_YposTwips;
#define somMD_VRPrinter_vrGet_YposTwips "----"
#define VRPrinter_vrGet_YposTwips(somSelf,val) \
    (SOM_Resolve(somSelf, VRPrinter, vrGet_YposTwips) \
	(somSelf,val))
#define _vrGet_YposTwips VRPrinter_vrGet_YposTwips

/*
 * New Method: vrRXMethod_ClosePrintJob
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_ClosePrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_ClosePrintJob, system)
typedef somTP_VRPrinter_vrRXMethod_ClosePrintJob *somTD_VRPrinter_vrRXMethod_ClosePrintJob;
#define somMD_VRPrinter_vrRXMethod_ClosePrintJob "----"
#define VRPrinter_vrRXMethod_ClosePrintJob(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_ClosePrintJob) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_ClosePrintJob VRPrinter_vrRXMethod_ClosePrintJob

/*
 * New Method: vrRXMethod_DefineTable
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_DefineTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_DefineTable, system)
typedef somTP_VRPrinter_vrRXMethod_DefineTable *somTD_VRPrinter_vrRXMethod_DefineTable;
#define somMD_VRPrinter_vrRXMethod_DefineTable "----"
#define VRPrinter_vrRXMethod_DefineTable(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_DefineTable) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_DefineTable VRPrinter_vrRXMethod_DefineTable

/*
 * New Method: vrRXMethod_EndRow
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_EndRow(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_EndRow, system)
typedef somTP_VRPrinter_vrRXMethod_EndRow *somTD_VRPrinter_vrRXMethod_EndRow;
#define somMD_VRPrinter_vrRXMethod_EndRow "----"
#define VRPrinter_vrRXMethod_EndRow(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_EndRow) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_EndRow VRPrinter_vrRXMethod_EndRow

/*
 * New Method: vrRXMethod_EndTable
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_EndTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_EndTable, system)
typedef somTP_VRPrinter_vrRXMethod_EndTable *somTD_VRPrinter_vrRXMethod_EndTable;
#define somMD_VRPrinter_vrRXMethod_EndTable "----"
#define VRPrinter_vrRXMethod_EndTable(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_EndTable) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_EndTable VRPrinter_vrRXMethod_EndTable

/*
 * New Method: vrRXMethod_GoTo
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_GoTo(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_GoTo, system)
typedef somTP_VRPrinter_vrRXMethod_GoTo *somTD_VRPrinter_vrRXMethod_GoTo;
#define somMD_VRPrinter_vrRXMethod_GoTo "----"
#define VRPrinter_vrRXMethod_GoTo(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_GoTo) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_GoTo VRPrinter_vrRXMethod_GoTo

/*
 * New Method: vrRXMethod_JobProperties
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_JobProperties(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_JobProperties, system)
typedef somTP_VRPrinter_vrRXMethod_JobProperties *somTD_VRPrinter_vrRXMethod_JobProperties;
#define somMD_VRPrinter_vrRXMethod_JobProperties "----"
#define VRPrinter_vrRXMethod_JobProperties(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_JobProperties) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_JobProperties VRPrinter_vrRXMethod_JobProperties

/*
 * New Method: vrRXMethod_PrintJustified
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintJustified(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintJustified, system)
typedef somTP_VRPrinter_vrRXMethod_PrintJustified *somTD_VRPrinter_vrRXMethod_PrintJustified;
#define somMD_VRPrinter_vrRXMethod_PrintJustified "----"
#define VRPrinter_vrRXMethod_PrintJustified(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintJustified) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintJustified VRPrinter_vrRXMethod_PrintJustified

/*
 * New Method: vrRXMethod_PrintCentered
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintCentered(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintCentered, system)
typedef somTP_VRPrinter_vrRXMethod_PrintCentered *somTD_VRPrinter_vrRXMethod_PrintCentered;
#define somMD_VRPrinter_vrRXMethod_PrintCentered "----"
#define VRPrinter_vrRXMethod_PrintCentered(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintCentered) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintCentered VRPrinter_vrRXMethod_PrintCentered

/*
 * New Method: vrRXMethod_PrintRight
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintRight(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintRight, system)
typedef somTP_VRPrinter_vrRXMethod_PrintRight *somTD_VRPrinter_vrRXMethod_PrintRight;
#define somMD_VRPrinter_vrRXMethod_PrintRight "----"
#define VRPrinter_vrRXMethod_PrintRight(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintRight) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintRight VRPrinter_vrRXMethod_PrintRight

/*
 * New Method: vrRXMethod_PrintLeft
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintLeft(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintLeft, system)
typedef somTP_VRPrinter_vrRXMethod_PrintLeft *somTD_VRPrinter_vrRXMethod_PrintLeft;
#define somMD_VRPrinter_vrRXMethod_PrintLeft "----"
#define VRPrinter_vrRXMethod_PrintLeft(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintLeft) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintLeft VRPrinter_vrRXMethod_PrintLeft

/*
 * New Method: vrRXMethod_PrintLine
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintLine(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintLine, system)
typedef somTP_VRPrinter_vrRXMethod_PrintLine *somTD_VRPrinter_vrRXMethod_PrintLine;
#define somMD_VRPrinter_vrRXMethod_PrintLine "----"
#define VRPrinter_vrRXMethod_PrintLine(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintLine) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintLine VRPrinter_vrRXMethod_PrintLine

/*
 * New Method: vrRXMethod_PrintBox
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintBox(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintBox, system)
typedef somTP_VRPrinter_vrRXMethod_PrintBox *somTD_VRPrinter_vrRXMethod_PrintBox;
#define somMD_VRPrinter_vrRXMethod_PrintBox "----"
#define VRPrinter_vrRXMethod_PrintBox(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintBox) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintBox VRPrinter_vrRXMethod_PrintBox

/*
 * New Method: vrRXMethod_PrintBitmap
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintBitmap(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintBitmap, system)
typedef somTP_VRPrinter_vrRXMethod_PrintBitmap *somTD_VRPrinter_vrRXMethod_PrintBitmap;
#define somMD_VRPrinter_vrRXMethod_PrintBitmap "----"
#define VRPrinter_vrRXMethod_PrintBitmap(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintBitmap) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintBitmap VRPrinter_vrRXMethod_PrintBitmap

/*
 * New Method: vrRXMethod_PrintFile
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintFile(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintFile, system)
typedef somTP_VRPrinter_vrRXMethod_PrintFile *somTD_VRPrinter_vrRXMethod_PrintFile;
#define somMD_VRPrinter_vrRXMethod_PrintFile "----"
#define VRPrinter_vrRXMethod_PrintFile(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintFile) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintFile VRPrinter_vrRXMethod_PrintFile

/*
 * New Method: vrRXMethod_StartCol
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_StartCol(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_StartCol, system)
typedef somTP_VRPrinter_vrRXMethod_StartCol *somTD_VRPrinter_vrRXMethod_StartCol;
#define somMD_VRPrinter_vrRXMethod_StartCol "----"
#define VRPrinter_vrRXMethod_StartCol(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_StartCol) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_StartCol VRPrinter_vrRXMethod_StartCol

/*
 * New Method: vrRXMethod_StartRow
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_StartRow(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_StartRow, system)
typedef somTP_VRPrinter_vrRXMethod_StartRow *somTD_VRPrinter_vrRXMethod_StartRow;
#define somMD_VRPrinter_vrRXMethod_StartRow "----"
#define VRPrinter_vrRXMethod_StartRow(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_StartRow) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_StartRow VRPrinter_vrRXMethod_StartRow

/*
 * New Method: vrRXMethod_StartTable
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_StartTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_StartTable, system)
typedef somTP_VRPrinter_vrRXMethod_StartTable *somTD_VRPrinter_vrRXMethod_StartTable;
#define somMD_VRPrinter_vrRXMethod_StartTable "----"
#define VRPrinter_vrRXMethod_StartTable(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_StartTable) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_StartTable VRPrinter_vrRXMethod_StartTable

/*
 * New Method: vrRXMethod_SetHeader
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetHeader, system)
typedef somTP_VRPrinter_vrRXMethod_SetHeader *somTD_VRPrinter_vrRXMethod_SetHeader;
#define somMD_VRPrinter_vrRXMethod_SetHeader "----"
#define VRPrinter_vrRXMethod_SetHeader(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetHeader) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetHeader VRPrinter_vrRXMethod_SetHeader

/*
 * New Method: vrRXMethod_SetHeaderMode
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetHeaderMode(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetHeaderMode, system)
typedef somTP_VRPrinter_vrRXMethod_SetHeaderMode *somTD_VRPrinter_vrRXMethod_SetHeaderMode;
#define somMD_VRPrinter_vrRXMethod_SetHeaderMode "----"
#define VRPrinter_vrRXMethod_SetHeaderMode(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetHeaderMode) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetHeaderMode VRPrinter_vrRXMethod_SetHeaderMode

/*
 * New Method: vrRXMethod_SetFooter
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetFooter(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetFooter, system)
typedef somTP_VRPrinter_vrRXMethod_SetFooter *somTD_VRPrinter_vrRXMethod_SetFooter;
#define somMD_VRPrinter_vrRXMethod_SetFooter "----"
#define VRPrinter_vrRXMethod_SetFooter(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetFooter) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetFooter VRPrinter_vrRXMethod_SetFooter

/*
 * New Method: vrRXMethod_SetMargins
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetMargins(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetMargins, system)
typedef somTP_VRPrinter_vrRXMethod_SetMargins *somTD_VRPrinter_vrRXMethod_SetMargins;
#define somMD_VRPrinter_vrRXMethod_SetMargins "----"
#define VRPrinter_vrRXMethod_SetMargins(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetMargins) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetMargins VRPrinter_vrRXMethod_SetMargins

/*
 * New Method: vrRXMethod_SetPrinter
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetPrinter(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetPrinter, system)
typedef somTP_VRPrinter_vrRXMethod_SetPrinter *somTD_VRPrinter_vrRXMethod_SetPrinter;
#define somMD_VRPrinter_vrRXMethod_SetPrinter "----"
#define VRPrinter_vrRXMethod_SetPrinter(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetPrinter) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetPrinter VRPrinter_vrRXMethod_SetPrinter

/*
 * New Method: vrRXMethod_PrinterDialog
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrinterDialog(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrinterDialog, system)
typedef somTP_VRPrinter_vrRXMethod_PrinterDialog *somTD_VRPrinter_vrRXMethod_PrinterDialog;
#define somMD_VRPrinter_vrRXMethod_PrinterDialog "----"
#define VRPrinter_vrRXMethod_PrinterDialog(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrinterDialog) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrinterDialog VRPrinter_vrRXMethod_PrinterDialog

/*
 * New Method: vrRXMethod_FontDialog
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_FontDialog(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_FontDialog, system)
typedef somTP_VRPrinter_vrRXMethod_FontDialog *somTD_VRPrinter_vrRXMethod_FontDialog;
#define somMD_VRPrinter_vrRXMethod_FontDialog "----"
#define VRPrinter_vrRXMethod_FontDialog(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_FontDialog) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_FontDialog VRPrinter_vrRXMethod_FontDialog

/*
 * New Method: vrRXMethod_OpenPrintJob
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_OpenPrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_OpenPrintJob, system)
typedef somTP_VRPrinter_vrRXMethod_OpenPrintJob *somTD_VRPrinter_vrRXMethod_OpenPrintJob;
#define somMD_VRPrinter_vrRXMethod_OpenPrintJob "----"
#define VRPrinter_vrRXMethod_OpenPrintJob(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_OpenPrintJob) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_OpenPrintJob VRPrinter_vrRXMethod_OpenPrintJob

/*
 * New Method: vrRXMethod_NewPage
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_NewPage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_NewPage, system)
typedef somTP_VRPrinter_vrRXMethod_NewPage *somTD_VRPrinter_vrRXMethod_NewPage;
#define somMD_VRPrinter_vrRXMethod_NewPage "----"
#define VRPrinter_vrRXMethod_NewPage(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_NewPage) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_NewPage VRPrinter_vrRXMethod_NewPage

/*
 * New Method: vrRXMethod_PrinterList
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrinterList(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrinterList, system)
typedef somTP_VRPrinter_vrRXMethod_PrinterList *somTD_VRPrinter_vrRXMethod_PrinterList;
#define somMD_VRPrinter_vrRXMethod_PrinterList "----"
#define VRPrinter_vrRXMethod_PrinterList(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrinterList) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrinterList VRPrinter_vrRXMethod_PrinterList

/*
 * New Method: vrRXMethod_Tab
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_Tab(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_Tab, system)
typedef somTP_VRPrinter_vrRXMethod_Tab *somTD_VRPrinter_vrRXMethod_Tab;
#define somMD_VRPrinter_vrRXMethod_Tab "----"
#define VRPrinter_vrRXMethod_Tab(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_Tab) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_Tab VRPrinter_vrRXMethod_Tab

/*
 * New Method: vrRXMethod_SetHeaderLineFont
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetHeaderLineFont(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetHeaderLineFont, system)
typedef somTP_VRPrinter_vrRXMethod_SetHeaderLineFont *somTD_VRPrinter_vrRXMethod_SetHeaderLineFont;
#define somMD_VRPrinter_vrRXMethod_SetHeaderLineFont "----"
#define VRPrinter_vrRXMethod_SetHeaderLineFont(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetHeaderLineFont) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetHeaderLineFont VRPrinter_vrRXMethod_SetHeaderLineFont

/*
 * New Method: vrRXMethod_PrintObjectImage
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintObjectImage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintObjectImage, system)
typedef somTP_VRPrinter_vrRXMethod_PrintObjectImage *somTD_VRPrinter_vrRXMethod_PrintObjectImage;
#define somMD_VRPrinter_vrRXMethod_PrintObjectImage "----"
#define VRPrinter_vrRXMethod_PrintObjectImage(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintObjectImage) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintObjectImage VRPrinter_vrRXMethod_PrintObjectImage

/*
 * New Method: vrRXMethod_ResetColHeader
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_ResetColHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_ResetColHeader, system)
typedef somTP_VRPrinter_vrRXMethod_ResetColHeader *somTD_VRPrinter_vrRXMethod_ResetColHeader;
#define somMD_VRPrinter_vrRXMethod_ResetColHeader "----"
#define VRPrinter_vrRXMethod_ResetColHeader(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_ResetColHeader) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_ResetColHeader VRPrinter_vrRXMethod_ResetColHeader

/*
 * New Method: vrRXMethod_ResetHeader
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_ResetHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_ResetHeader, system)
typedef somTP_VRPrinter_vrRXMethod_ResetHeader *somTD_VRPrinter_vrRXMethod_ResetHeader;
#define somMD_VRPrinter_vrRXMethod_ResetHeader "----"
#define VRPrinter_vrRXMethod_ResetHeader(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_ResetHeader) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_ResetHeader VRPrinter_vrRXMethod_ResetHeader

/*
 * New Method: vrRXMethod_AbortPrintJob
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_AbortPrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_AbortPrintJob, system)
typedef somTP_VRPrinter_vrRXMethod_AbortPrintJob *somTD_VRPrinter_vrRXMethod_AbortPrintJob;
#define somMD_VRPrinter_vrRXMethod_AbortPrintJob "----"
#define VRPrinter_vrRXMethod_AbortPrintJob(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_AbortPrintJob) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_AbortPrintJob VRPrinter_vrRXMethod_AbortPrintJob

/*
 * New Method: vrRXMethod_BlockFits
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_BlockFits(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_BlockFits, system)
typedef somTP_VRPrinter_vrRXMethod_BlockFits *somTD_VRPrinter_vrRXMethod_BlockFits;
#define somMD_VRPrinter_vrRXMethod_BlockFits "----"
#define VRPrinter_vrRXMethod_BlockFits(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_BlockFits) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_BlockFits VRPrinter_vrRXMethod_BlockFits

/*
 * New Method: vrRXMethod_LineFits
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_LineFits(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_LineFits, system)
typedef somTP_VRPrinter_vrRXMethod_LineFits *somTD_VRPrinter_vrRXMethod_LineFits;
#define somMD_VRPrinter_vrRXMethod_LineFits "----"
#define VRPrinter_vrRXMethod_LineFits(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_LineFits) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_LineFits VRPrinter_vrRXMethod_LineFits

/*
 * New Method: vrRXMethod_SetProgressTexts
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SetProgressTexts(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SetProgressTexts, system)
typedef somTP_VRPrinter_vrRXMethod_SetProgressTexts *somTD_VRPrinter_vrRXMethod_SetProgressTexts;
#define somMD_VRPrinter_vrRXMethod_SetProgressTexts "----"
#define VRPrinter_vrRXMethod_SetProgressTexts(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SetProgressTexts) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SetProgressTexts VRPrinter_vrRXMethod_SetProgressTexts

/*
 * New Method: vrRXMethod_MoveX
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_MoveX(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_MoveX, system)
typedef somTP_VRPrinter_vrRXMethod_MoveX *somTD_VRPrinter_vrRXMethod_MoveX;
#define somMD_VRPrinter_vrRXMethod_MoveX "----"
#define VRPrinter_vrRXMethod_MoveX(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_MoveX) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_MoveX VRPrinter_vrRXMethod_MoveX

/*
 * New Method: vrRXMethod_MoveY
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_MoveY(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_MoveY, system)
typedef somTP_VRPrinter_vrRXMethod_MoveY *somTD_VRPrinter_vrRXMethod_MoveY;
#define somMD_VRPrinter_vrRXMethod_MoveY "----"
#define VRPrinter_vrRXMethod_MoveY(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_MoveY) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_MoveY VRPrinter_vrRXMethod_MoveY

/*
 * New Method: vrRXMethod_PrintWinImage
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintWinImage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintWinImage, system)
typedef somTP_VRPrinter_vrRXMethod_PrintWinImage *somTD_VRPrinter_vrRXMethod_PrintWinImage;
#define somMD_VRPrinter_vrRXMethod_PrintWinImage "----"
#define VRPrinter_vrRXMethod_PrintWinImage(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintWinImage) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintWinImage VRPrinter_vrRXMethod_PrintWinImage

/*
 * New Method: vrRXMethod_LoadResMod
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_LoadResMod(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_LoadResMod, system)
typedef somTP_VRPrinter_vrRXMethod_LoadResMod *somTD_VRPrinter_vrRXMethod_LoadResMod;
#define somMD_VRPrinter_vrRXMethod_LoadResMod "----"
#define VRPrinter_vrRXMethod_LoadResMod(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_LoadResMod) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_LoadResMod VRPrinter_vrRXMethod_LoadResMod

/*
 * New Method: vrRXMethod_FreeResMod
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_FreeResMod(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_FreeResMod, system)
typedef somTP_VRPrinter_vrRXMethod_FreeResMod *somTD_VRPrinter_vrRXMethod_FreeResMod;
#define somMD_VRPrinter_vrRXMethod_FreeResMod "----"
#define VRPrinter_vrRXMethod_FreeResMod(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_FreeResMod) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_FreeResMod VRPrinter_vrRXMethod_FreeResMod

/*
 * New Method: vrRXMethod_PrintJPEG
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintJPEG(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintJPEG, system)
typedef somTP_VRPrinter_vrRXMethod_PrintJPEG *somTD_VRPrinter_vrRXMethod_PrintJPEG;
#define somMD_VRPrinter_vrRXMethod_PrintJPEG "----"
#define VRPrinter_vrRXMethod_PrintJPEG(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintJPEG) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintJPEG VRPrinter_vrRXMethod_PrintJPEG

/*
 * New Method: vrRXMethod_StringLength
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_StringLength(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_StringLength, system)
typedef somTP_VRPrinter_vrRXMethod_StringLength *somTD_VRPrinter_vrRXMethod_StringLength;
#define somMD_VRPrinter_vrRXMethod_StringLength "----"
#define VRPrinter_vrRXMethod_StringLength(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_StringLength) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_StringLength VRPrinter_vrRXMethod_StringLength

/*
 * New Method: vrRXMethod_GotoX
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_GotoX(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_GotoX, system)
typedef somTP_VRPrinter_vrRXMethod_GotoX *somTD_VRPrinter_vrRXMethod_GotoX;
#define somMD_VRPrinter_vrRXMethod_GotoX "----"
#define VRPrinter_vrRXMethod_GotoX(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_GotoX) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_GotoX VRPrinter_vrRXMethod_GotoX

/*
 * New Method: vrRXMethod_GotoY
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_GotoY(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_GotoY, system)
typedef somTP_VRPrinter_vrRXMethod_GotoY *somTD_VRPrinter_vrRXMethod_GotoY;
#define somMD_VRPrinter_vrRXMethod_GotoY "----"
#define VRPrinter_vrRXMethod_GotoY(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_GotoY) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_GotoY VRPrinter_vrRXMethod_GotoY

/*
 * New Method: vrRXMethod_GotoTab
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_GotoTab(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_GotoTab, system)
typedef somTP_VRPrinter_vrRXMethod_GotoTab *somTD_VRPrinter_vrRXMethod_GotoTab;
#define somMD_VRPrinter_vrRXMethod_GotoTab "----"
#define VRPrinter_vrRXMethod_GotoTab(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_GotoTab) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_GotoTab VRPrinter_vrRXMethod_GotoTab

/*
 * New Method: vrRXMethod_DrawLine
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_DrawLine(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_DrawLine, system)
typedef somTP_VRPrinter_vrRXMethod_DrawLine *somTD_VRPrinter_vrRXMethod_DrawLine;
#define somMD_VRPrinter_vrRXMethod_DrawLine "----"
#define VRPrinter_vrRXMethod_DrawLine(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_DrawLine) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_DrawLine VRPrinter_vrRXMethod_DrawLine

/*
 * New Method: vrRXMethod_PrintBullet
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_PrintBullet(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_PrintBullet, system)
typedef somTP_VRPrinter_vrRXMethod_PrintBullet *somTD_VRPrinter_vrRXMethod_PrintBullet;
#define somMD_VRPrinter_vrRXMethod_PrintBullet "----"
#define VRPrinter_vrRXMethod_PrintBullet(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_PrintBullet) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_PrintBullet VRPrinter_vrRXMethod_PrintBullet

/*
 * New Method: vrRXMethod_SaveJobProps
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_SaveJobProps(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_SaveJobProps, system)
typedef somTP_VRPrinter_vrRXMethod_SaveJobProps *somTD_VRPrinter_vrRXMethod_SaveJobProps;
#define somMD_VRPrinter_vrRXMethod_SaveJobProps "----"
#define VRPrinter_vrRXMethod_SaveJobProps(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_SaveJobProps) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_SaveJobProps VRPrinter_vrRXMethod_SaveJobProps

/*
 * New Method: vrRXMethod_ReadJobProps
 */
typedef bool    SOMLINK somTP_VRPrinter_vrRXMethod_ReadJobProps(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata);
#pragma linkage(somTP_VRPrinter_vrRXMethod_ReadJobProps, system)
typedef somTP_VRPrinter_vrRXMethod_ReadJobProps *somTD_VRPrinter_vrRXMethod_ReadJobProps;
#define somMD_VRPrinter_vrRXMethod_ReadJobProps "----"
#define VRPrinter_vrRXMethod_ReadJobProps(somSelf,argc,argv,argsused,retstr,rxdata) \
    (SOM_Resolve(somSelf, VRPrinter, vrRXMethod_ReadJobProps) \
	(somSelf,argc,argv,argsused,retstr,rxdata))
#define _vrRXMethod_ReadJobProps VRPrinter_vrRXMethod_ReadJobProps

/*
 * New Method: vrWM_INITCAP
 */
typedef MRESULT    SOMLINK somTP_VRPrinter_vrWM_INITCAP(VRPrinter *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2);
#pragma linkage(somTP_VRPrinter_vrWM_INITCAP, system)
typedef somTP_VRPrinter_vrWM_INITCAP *somTD_VRPrinter_vrWM_INITCAP;
#define somMD_VRPrinter_vrWM_INITCAP "----"
#define VRPrinter_vrWM_INITCAP(somSelf,hWnd,msg,mp1,mp2) \
    (SOM_Resolve(somSelf, VRPrinter, vrWM_INITCAP) \
	(somSelf,hWnd,msg,mp1,mp2))
#define _vrWM_INITCAP VRPrinter_vrWM_INITCAP

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK VRPrinterNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(VRPrinterNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct VRPrinterClassDataStructure {
	SOMAny *classObject;
	somMToken vrStemFetchLong;
	somMToken vrStemFetchString;
	somMToken vrStemSetValue;
	somMToken vrStemSetValueLong;
	somMToken vrGet_LeftMargin;
	somMToken vrGet_RightMargin;
	somMToken vrGet_TopMargin;
	somMToken vrGet_BottomMargin;
	somMToken vrGet_PageWidth;
	somMToken vrGet_PageHeight;
	somMToken vrGet_Printing;
	somMToken vrGet_CurrentPrinter;
	somMToken vrGet_CurrentDevice;
	somMToken vrSet_LineSpace;
	somMToken vrGet_LineSpace;
	somMToken vrGet_Version;
	somMToken vrSet_PrintColor;
	somMToken vrGet_PrintColor;
	somMToken vrSet_ColorEnabled;
	somMToken vrGet_ColorEnabled;
	somMToken vrSet_Measures;
	somMToken vrGet_Measures;
	somMToken vrGet_PageNum;
	somMToken vrGet_JobName;
	somMToken vrGet_DefaultPrinter;
	somMToken vrGet_MinLeftMar;
	somMToken vrGet_MinRightMar;
	somMToken vrGet_MinTopMar;
	somMToken vrGet_MinBottomMar;
	somMToken vrGet_FormName;
	somMToken vrGet_FormWidth;
	somMToken vrGet_FormHeight;
	somMToken vrSet_ShowProgress;
	somMToken vrGet_ShowProgress;
	somMToken vrGet_XPos;
	somMToken vrGet_YPos;
	somMToken vrGet_XposTwips;
	somMToken vrGet_YposTwips;
	somMToken vrRXMethod_ClosePrintJob;
	somMToken vrRXMethod_DefineTable;
	somMToken vrRXMethod_EndRow;
	somMToken vrRXMethod_EndTable;
	somMToken vrRXMethod_GoTo;
	somMToken vrRXMethod_JobProperties;
	somMToken vrRXMethod_PrintJustified;
	somMToken vrRXMethod_PrintCentered;
	somMToken vrRXMethod_PrintRight;
	somMToken vrRXMethod_PrintLeft;
	somMToken vrRXMethod_PrintLine;
	somMToken vrRXMethod_PrintBox;
	somMToken vrRXMethod_PrintBitmap;
	somMToken vrRXMethod_PrintFile;
	somMToken vrRXMethod_StartCol;
	somMToken vrRXMethod_StartRow;
	somMToken vrRXMethod_StartTable;
	somMToken vrRXMethod_SetHeader;
	somMToken vrRXMethod_SetHeaderMode;
	somMToken vrRXMethod_SetFooter;
	somMToken vrRXMethod_SetMargins;
	somMToken vrRXMethod_SetPrinter;
	somMToken vrRXMethod_PrinterDialog;
	somMToken vrRXMethod_FontDialog;
	somMToken vrRXMethod_OpenPrintJob;
	somMToken vrRXMethod_NewPage;
	somMToken vrRXMethod_PrinterList;
	somMToken vrRXMethod_Tab;
	somMToken vrRXMethod_SetHeaderLineFont;
	somMToken vrRXMethod_PrintObjectImage;
	somMToken vrRXMethod_ResetColHeader;
	somMToken vrRXMethod_ResetHeader;
	somMToken vrRXMethod_AbortPrintJob;
	somMToken vrRXMethod_BlockFits;
	somMToken vrRXMethod_LineFits;
	somMToken vrRXMethod_SetProgressTexts;
	somMToken vrRXMethod_MoveX;
	somMToken vrRXMethod_MoveY;
	somMToken vrRXMethod_PrintWinImage;
	somMToken vrRXMethod_LoadResMod;
	somMToken vrRXMethod_FreeResMod;
	somMToken vrRXMethod_PrintJPEG;
	somMToken vrRXMethod_StringLength;
	somMToken vrRXMethod_GotoX;
	somMToken vrRXMethod_GotoY;
	somMToken vrRXMethod_GotoTab;
	somMToken vrRXMethod_DrawLine;
	somMToken vrRXMethod_PrintBullet;
	somMToken vrWM_INITCAP;
	somMToken vrRXMethod_SaveJobProps;
	somMToken vrRXMethod_ReadJobProps;
} VRPrinterClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct VRPrinterCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} VRPrinterCClassData;

#endif       /* printer_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: printer.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef printer_mh
#define printer_mh


/*
 * Define the class name as an object type
 */
#ifndef M_VRPrinter
#define M_VRPrinter SOMAny
#endif

#define M_VRPrinter_MajorVersion 1
#define M_VRPrinter_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_VRPrinterNewClass c
#pragma linkage(c, system)
#define M_VRPrinterClassData d
#define M_VRPrinterCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_VRPrinter_classObj M_VRPrinterClassData.classObject
#define _M_VRPrinter M_VRPrinter_classObj

/*
 * New and Renew macros for M_VRPrinter
 */
#define _M_VRPrinterNew() (_somNew(M_VRPrinterClassData.classObject))
#define M_VRPrinterNew() \
	( M_VRPrinterClassData.classObject \
		? _M_VRPrinterNew() \
		: ( M_VRPrinterNewClass(M_VRPrinter_MajorVersion, M_VRPrinter_MinorVersion), _M_VRPrinterNew() ) )
#define M_VRPrinterRenew(buf) \
	( _somRenew(M_VRPrinterClassData.classObject, buf) )

/*
 * Override method: vrLocalClassInit
 */
#define M_VRPrinter_vrLocalClassInit(somSelf) \
	M_VRCore_vrLocalClassInit(somSelf)

/*
 * Override method: vrLocalWindowClassInit
 */
#define M_VRPrinter_vrLocalWindowClassInit(somSelf) \
	M_VRCore_vrLocalWindowClassInit(somSelf)

/*
 * Override method: somInit
 */
#define M_VRPrinter_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * Override method: somUninit
 */
#define M_VRPrinter_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: vrShowHelp
 */
typedef bool    SOMLINK somTP_M_VRPrinter_vrShowHelp(M_VRPrinter *somSelf,
		HWND root_frame);
#pragma linkage(somTP_M_VRPrinter_vrShowHelp, system)
typedef somTP_M_VRPrinter_vrShowHelp *somTD_M_VRPrinter_vrShowHelp;
#define somMD_M_VRPrinter_vrShowHelp "----"
#define M_VRPrinter_vrShowHelp(somSelf,root_frame) \
    (SOM_Resolve(somSelf, M_VRPrinter, vrShowHelp) \
	(somSelf,root_frame))
#define _vrShowHelp M_VRPrinter_vrShowHelp

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_VRPrinterNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_VRPrinterNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_VRPrinterClassDataStructure {
	SOMAny *classObject;
	somMToken vrShowHelp;
} M_VRPrinterClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_VRPrinterCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_VRPrinterCClassData;

#endif       /* printer_h */
