
/*
 * This file was generated by the SOM Compiler.
 * FileName: printer.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define VRPrinter_Class_Source
#include "printer.ih"

/*
 *  VRPrinterInstance_somInit
 */

SOM_Scope void   SOMLINK VRPrinterInstance_somInit(VRPrinter *somSelf)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_somInit");

    parent_somInit(somSelf);
}

/*
 *  VRPrinterInstance_somUninit
 */

SOM_Scope void   SOMLINK VRPrinterInstance_somUninit(VRPrinter *somSelf)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_somUninit");

    parent_somUninit(somSelf);
}

/*
 *  VRPrinterInstance_vrLocalCreateWindow
 */

SOM_Scope HWND   SOMLINK VRPrinterInstance_vrLocalCreateWindow(VRPrinter *somSelf,
		PBOOL visible)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrLocalCreateWindow");

    return (parent_vrLocalCreateWindow(somSelf,visible));
}

/*
 *  VRPrinterInstance_vrStemFetchLong
 */

SOM_Scope ULONG   SOMLINK VRPrinterInstance_vrStemFetchLong(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PBOOL pOk)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrStemFetchLong");

    return (ULONG) 0;
}

/*
 *  VRPrinterInstance_vrStemFetchString
 */

SOM_Scope PSZ   SOMLINK VRPrinterInstance_vrStemFetchString(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PBOOL pOk)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrStemFetchString");

    return (PSZ) 0;
}

/*
 *  VRPrinterInstance_vrStemSetValue
 */

SOM_Scope BOOL   SOMLINK VRPrinterInstance_vrStemSetValue(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		PSZ pszValue)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrStemSetValue");

    return (BOOL) 0;
}

/*
 *  VRPrinterInstance_vrStemSetValueLong
 */

SOM_Scope BOOL   SOMLINK VRPrinterInstance_vrStemSetValueLong(VRPrinter *somSelf,
		PSZ pszStem,
		ULONG index,
		ULONG ulValue)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrStemSetValueLong");

    return (BOOL) 0;
}

/*
 *  VRPrinterInstance_vrGet_LeftMargin
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_LeftMargin(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_LeftMargin");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_RightMargin
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_RightMargin(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_RightMargin");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_TopMargin
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_TopMargin(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_TopMargin");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_BottomMargin
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_BottomMargin(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_BottomMargin");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_PageWidth
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_PageWidth(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_PageWidth");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_PageHeight
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_PageHeight(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_PageHeight");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_Printing
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_Printing(VRPrinter *somSelf,
		BOOL *on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_Printing");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_CurrentPrinter
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_CurrentPrinter(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_CurrentPrinter");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_CurrentDevice
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_CurrentDevice(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_CurrentDevice");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrSet_LineSpace
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_LineSpace(VRPrinter *somSelf,
		ULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_LineSpace");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_LineSpace
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_LineSpace(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_LineSpace");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_Version
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_Version(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_Version");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrSet_PrintColor
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_PrintColor(VRPrinter *somSelf,
		PSZ str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_PrintColor");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_PrintColor
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_PrintColor(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_PrintColor");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrSet_ColorEnabled
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_ColorEnabled(VRPrinter *somSelf,
		BOOL on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_ColorEnabled");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_ColorEnabled
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_ColorEnabled(VRPrinter *somSelf,
		BOOL *on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_ColorEnabled");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrSet_Measures
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_Measures(VRPrinter *somSelf,
		PSZ str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_Measures");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_Measures
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_Measures(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_Measures");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_PageNum
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_PageNum(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_PageNum");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_JobName
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_JobName(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_JobName");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_DefaultPrinter
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_DefaultPrinter(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_DefaultPrinter");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_MinLeftMar
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_MinLeftMar(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_MinLeftMar");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_MinRightMar
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_MinRightMar(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_MinRightMar");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_MinTopMar
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_MinTopMar(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_MinTopMar");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_MinBottomMar
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_MinBottomMar(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_MinBottomMar");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_FormName
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_FormName(VRPrinter *somSelf,
		PSZ *str)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_FormName");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_FormWidth
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_FormWidth(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_FormWidth");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_FormHeight
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_FormHeight(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_FormHeight");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrSet_WordBreak
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_WordBreak(VRPrinter *somSelf,
		BOOL on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_WordBreak");

    return (parent_vrSet_WordBreak(somSelf,on));
}

/*
 *  VRPrinterInstance_vrGet_WordBreak
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_WordBreak(VRPrinter *somSelf,
		BOOL *on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_WordBreak");

    return (parent_vrGet_WordBreak(somSelf,on));
}

/*
 *  VRPrinterInstance_vrSet_ShowProgress
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrSet_ShowProgress(VRPrinter *somSelf,
		BOOL on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrSet_ShowProgress");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_ShowProgress
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_ShowProgress(VRPrinter *somSelf,
		BOOL *on)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_ShowProgress");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_XPos
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_XPos(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_XPos");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_YPos
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_YPos(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_YPos");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_XposTwips
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_XposTwips(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_XposTwips");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrGet_YposTwips
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrGet_YposTwips(VRPrinter *somSelf,
		PULONG val)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrGet_YposTwips");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_ClosePrintJob
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_ClosePrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_ClosePrintJob");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_DefineTable
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_DefineTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_DefineTable");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_EndRow
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_EndRow(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_EndRow");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_EndTable
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_EndTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_EndTable");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_GoTo
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_GoTo(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_GoTo");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_JobProperties
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_JobProperties(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_JobProperties");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintJustified
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintJustified(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintJustified");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintCentered
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintCentered(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintCentered");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintRight
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintRight(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintRight");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintLeft
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintLeft(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintLeft");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintLine
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintLine(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintLine");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintBox
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintBox(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintBox");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintBitmap
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintBitmap(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintBitmap");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintFile
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintFile(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintFile");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_StartCol
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_StartCol(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_StartCol");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_StartRow
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_StartRow(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_StartRow");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_StartTable
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_StartTable(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_StartTable");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetHeader
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetHeader");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetHeaderMode
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetHeaderMode(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetHeaderMode");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetFooter
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetFooter(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetFooter");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetMargins
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetMargins(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetMargins");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetPrinter
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetPrinter(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetPrinter");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrinterDialog
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrinterDialog(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrinterDialog");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_FontDialog
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_FontDialog(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_FontDialog");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_OpenPrintJob
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_OpenPrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_OpenPrintJob");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_NewPage
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_NewPage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_NewPage");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrinterList
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrinterList(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrinterList");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_Tab
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_Tab(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_Tab");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetHeaderLineFont
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetHeaderLineFont(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetHeaderLineFont");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintObjectImage
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintObjectImage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintObjectImage");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_ResetColHeader
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_ResetColHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_ResetColHeader");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_ResetHeader
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_ResetHeader(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_ResetHeader");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_AbortPrintJob
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_AbortPrintJob(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_AbortPrintJob");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_BlockFits
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_BlockFits(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_BlockFits");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_LineFits
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_LineFits(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_LineFits");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SetProgressTexts
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SetProgressTexts(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SetProgressTexts");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_MoveX
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_MoveX(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_MoveX");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_MoveY
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_MoveY(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_MoveY");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintWinImage
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintWinImage(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintWinImage");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_LoadResMod
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_LoadResMod(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_LoadResMod");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_FreeResMod
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_FreeResMod(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_FreeResMod");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintJPEG
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintJPEG(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintJPEG");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_StringLength
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_StringLength(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_StringLength");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_GotoX
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_GotoX(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_GotoX");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_GotoY
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_GotoY(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_GotoY");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_GotoTab
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_GotoTab(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_GotoTab");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_DrawLine
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_DrawLine(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_DrawLine");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_PrintBullet
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_PrintBullet(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_PrintBullet");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_SaveJobProps
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_SaveJobProps(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_SaveJobProps");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrRXMethod_ReadJobProps
 */

SOM_Scope bool   SOMLINK VRPrinterInstance_vrRXMethod_ReadJobProps(VRPrinter *somSelf,
		LONG argc,
		PRXSTRING argv,
		PLONG argsused,
		PRXSTRING retstr,
		PVRMETHEXTRA rxdata)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrRXMethod_ReadJobProps");

    return (bool) 0;
}

/*
 *  VRPrinterInstance_vrWM_INITCAP
 */

SOM_Scope MRESULT   SOMLINK VRPrinterInstance_vrWM_INITCAP(VRPrinter *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2)
{
    VRPrinterData *somThis = VRPrinterGetData(somSelf);
    VRPrinterMethodDebug("VRPrinter","VRPrinterInstance_vrWM_INITCAP");

    return (MRESULT) 0;
}

#undef SOM_CurrentClass
#define SOM_CurrentClass SOMMeta
/*
 *  VRPrinterClass_vrLocalClassInit
 */

SOM_Scope bool   SOMLINK VRPrinterClass_vrLocalClassInit(M_VRPrinter *somSelf)
{
    /* M_VRPrinterData *somThis = M_VRPrinterGetData(somSelf); */
    M_VRPrinterMethodDebug("M_VRPrinter","VRPrinterClass_vrLocalClassInit");

    return (parent_vrLocalClassInit(somSelf));
}

/*
 *  VRPrinterClass_vrLocalWindowClassInit
 */

SOM_Scope bool   SOMLINK VRPrinterClass_vrLocalWindowClassInit(M_VRPrinter *somSelf)
{
    /* M_VRPrinterData *somThis = M_VRPrinterGetData(somSelf); */
    M_VRPrinterMethodDebug("M_VRPrinter","VRPrinterClass_vrLocalWindowClassInit");

    return (parent_vrLocalWindowClassInit(somSelf));
}

/*
 *  VRPrinterClass_somInit
 */

SOM_Scope void   SOMLINK VRPrinterClass_somInit(M_VRPrinter *somSelf)
{
    /* M_VRPrinterData *somThis = M_VRPrinterGetData(somSelf); */
    M_VRPrinterMethodDebug("M_VRPrinter","VRPrinterClass_somInit");

    parent_somInit(somSelf);
}

/*
 *  VRPrinterClass_somUninit
 */

SOM_Scope void   SOMLINK VRPrinterClass_somUninit(M_VRPrinter *somSelf)
{
    /* M_VRPrinterData *somThis = M_VRPrinterGetData(somSelf); */
    M_VRPrinterMethodDebug("M_VRPrinter","VRPrinterClass_somUninit");

    parent_somUninit(somSelf);
}

/*
 *  VRPrinterClass_vrShowHelp
 */

SOM_Scope bool   SOMLINK VRPrinterClass_vrShowHelp(M_VRPrinter *somSelf,
		HWND root_frame)
{
    /* M_VRPrinterData *somThis = M_VRPrinterGetData(somSelf); */
    M_VRPrinterMethodDebug("M_VRPrinter","VRPrinterClass_vrShowHelp");

    return (bool) 0;
}
